language: go
go:
  - 1.9

before_install:
  - sudo apt-get update -y
  - sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev -y

install:
  - go get -u github.com/golang/dep/cmd/dep
  - make vendor

script:
  - make test
