language: go
go:
  - 1.9

before_install:
  - sudo apt-get update -y
  - sudo apt-get install libasound2-dev libxi-dev libxinerama-dev libxcursor-dev libxxf86vm-dev libxrandr-dev -y

install:
  - go get -u github.com/golang/dep/cmd/dep
  - make vendor

script:
  - make test
